### PR TITLE
Port from atom-parinfer

### PR DESCRIPTION
**Pull request by roman01la**
Hi!

Current vscode-parinfer uses an old version of Parinfer and it doesn't work good. I've ported a great atom-parinfer plugin to VS Code and updated Parinfer to v2.0.10.

It would be great to have this merged. I've been using Atom and now switched to Code and this plugin is the essential tool.

Thanks!

### CODE REVIEW

**Comment by indiejames** [comment]
Please take a look at this and merge it soon. I cloned roman01la's repository to test this and it is a big improvement over the current master.

**Comment by shaunlebron** [comment]
@narma: would you mind if I took ownership of this project?

Parinfer core is pretty close to complete now after a year of focusing on that. I'd like to maintain a good plugin to make use of it now and help with big PRs like this.

Thanks for upgrading it and picking it up last year. Let me know if you wanna hand off the torch.  Glad to take it.

**Comment by narma** [comment]
@shaunlebron Sure! Thanks for catching this up. I mostly write Scala code rather than Clojure, and for Clojure now using Cursive (mostly) instead of vscode.

**Comment by narma** [comment]
@shaunlebron I can't transfer ownership because of `shaunlebron/vscode-parinfer` already exists

**Comment by shaunlebron** [comment]
@narma: just deleted my fork, should be clear for the transfer now, thanks

**Comment by shaunlebron** [comment]
@roman01la I'll publish this tonight after I figure it out

**Comment by shaunlebron** [comment]
published, will try to get the obsolete parinfer packages removed from marketplace to avoid confusion

**Comment by oakmac** [comment]
@roman01la This is a great improvement to vscode-parinfer. Thank you for doing this work!

**Pull request merged**
